added unpacking plugin for tenvis pk2 container
fkie-cad/fact_extractor pull request #148
Opened 2024-08-12 13:51 UTC by jstucke

needs MIME type for pk2 first

2025-01-22 12:54 UTC, dorpvom requested changes
Minor request for change

2025-01-22 12:54 UTC, dorpvom commented on fact_extractor/plugins/unpacking/tenvis_pk2/code/tenvis_pk2.py
> +        meta['errors'] = ['file too small']
There can always only be one error based on this data flow, no? Then we should call this `error`  (singular)

2025-01-22 13:15 UTC, jstucke commented on fact_extractor/plugins/unpacking/tenvis_pk2/code/tenvis_pk2.py
> +        meta['errors'] = ['file too small']
There can be multiple errors in the lower part of the function (where `meta.setdefault('errors', []).append()` is used). I wanted to keep the metadata consistent (even if there can be only one error in this case).

2025-01-22 13:35 UTC, dorpvom commented on fact_extractor/plugins/unpacking/tenvis_pk2/code/tenvis_pk2.py
> +        meta['errors'] = ['file too small']
I don't see how. There is only one item given to the `append` and there is a break directly behind. In any case: Consistent with what?

2025-01-23 10:48 UTC, jstucke commented on fact_extractor/plugins/unpacking/tenvis_pk2/code/tenvis_pk2.py
> +        meta['errors'] = ['file too small']
I see now what you mean -> fixed

2025-01-23 15:10 UTC, dorpvom approved these changes

2025-01-23 15:10 UTC, merged